### Generated by rprotoc. DO NOT EDIT!
### <proto file: ClockEntry.proto>
# message ClockEntry {
#    required int32 node_id = 1;
#    required int64 version = 2;
# }
#

require 'protobuf/message/message'
require 'protobuf/message/enum'
require 'protobuf/message/service'
require 'protobuf/message/extend'

class ClockEntry < ::Protobuf::Message
  defined_in __FILE__
  required :int32, :node_id, 1
  required :int64, :version, 2
end

ce = ClockEntry.new
ce.node_id = 12
ce.version = 12345
print ce.to_s

